services:
  frontend:
    build: 
      context: .
      dockerfile: services/frontend/Dockerfile
    ports:
      - "3000:3000"
    command: "npm start"
  
  document-service:
    build:
      context: .
      dockerfile: services/document-service/Dockerfile
    ports:
      - "8000:8000"